import { Dict } from '@yogurtcat/lib';
import { element, codes, parser, sifter, creator, paramode } from './util';
export default class Context {
    readonly syms: Dict<string, string>;
    readonly vars: Dict<string, (string | element)[]>;
    readonly parsers: Dict<string, parser>;
    readonly sifters: Dict<string, sifter[]>;
    readonly creators: Dict<string, creator>;
    readonly paramode: paramode;
    constructor();
    parse(text: string): codes[];
    parseVars(element: element): element;
    parseElems(element: element): element;
    parseChildrenVars(element: element): element;
    parseChildrenContinue(element: element): element;
    parseChildrenJoin(element: element, sep?: string): element;
    parseChildrenSplit(element: element): element;
    parseChildrenDelEmpty(element: element): element;
    parseChildrenLines(element: element): element;
    parseChildrenNewLines(element: element): element;
    parseChildrenJoinLines(element: element): element;
    parseChildrenDelStrs(element: element): element;
    parseChildrenDelElems(element: element): element;
    parseChildrenClosure(element: element): element;
    parseChildrenCopyStatus(element: element): element;
    parseChildrenParsers(element: element): codes[];
    parseParsers(element: element): codes[];
    parseSifters(element: element): codes[];
    createElement(sym: string, status: any, attrs: any[], children: any[]): codes[];
    parseCreate(element: element): codes[];
}
