declare const _default: () => {
    main: string;
    def: string;
    var: string;
    continue: string;
    closure: string;
    article: string;
    section: string;
    figure: string;
    paragraph: string;
    headline: string;
    caption: string;
    align: string;
    color: string;
    highlight: string;
    bold: string;
    italic: string;
    underline: string;
    strike: string;
    superscript: string;
    subscript: string;
    hyperlink: string;
    space: string;
    newline: string;
    separate: string;
    image: string;
    formula: string;
    quote: string;
    code: string;
    keyboard: string;
    list: string;
    table: string;
    audio: string;
    video: string;
};
export default _default;
